/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package botique.system;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;



/**
 *
 * @author Admin
 */
public class frmCreateInvoice extends javax.swing.JFrame {
    String sqlcode;
    Connection conn = null;
    ResultSet rs = null;
    Statement stmt = null;
    String refid;
   
    
    /**
     * Creates new form frmCreateInvoice
     */
    public frmCreateInvoice() {
        initComponents();
        lbluser.setText(BotiqueSystem.user);
        conn=BotiqueSystem.conn_db();
        //invoice no should be autogenerated
        loadinvoice();
        txtinvoicedate.setText(BotiqueSystem.strdatenow());
          Timer t= new Timer(1000, dateTime);  
          t.start();
          btnedit.setEnabled(false);
          
          txtinvoiceno.setText("INV"+BotiqueSystem.nextInvoiceNo());
          bg1.add(rbtgov);
          bg1.add(rbtprivate);
         
         
    
    }
    public void cleartxt(){
        txtcustomercode.setText(null);
        txtcustomerdetails.setText(null);
       // txtinvoiceno.setText(null);
    }    
    
        public void loadinvoice(){
            DefaultTableModel dtm = new DefaultTableModel(){
                public boolean isCellEditable(int rowIndex, int colIndex){
                    return false;
                }
            };
           
            dtm.addColumn("Invoice no");
            dtm.addColumn("Invoice Date");
            dtm.addColumn("Name");
            
           
            
              dtm.addColumn("Address");
               dtm.addColumn("Customer Code");
                
                
                
                sqlcode="select "
                        + " tblinvoiceno.fld_invoice_no,"
                        + " date_format(tblinvoiceno.fld_invoice_date, '%m-%d-%Y'),"
                        + " tblcustomer.fld_customer_code, "
                        + "tblcustomer.fld_fname, "
                        + "tblcustomer.fld_mname,"
                        + " tblcustomer.fld_lname, "
                        + "tblcustomer.fld_zone, "
                        + "tblcustomer.fld_st, "
                        + "tblcustomer.fld_city, "
                        + "tblcustomer.fld_province "
                        + "from tblinvoiceno inner join"
                        + " tblcustomer on tblinvoiceno.fld_customer_code=tblcustomer.fld_customer_code "
                        + " order by tblinvoiceno.fld_invoice_no desc";
            try {
                  rs=BotiqueSystem.selectquery(sqlcode, conn);
                  
                while (rs.next()) {
                    dtm.addRow(new Object[]{
                        
                        rs.getString("tblinvoiceno.fld_invoice_no"),
                        rs.getString("date_format(tblinvoiceno.fld_invoice_date, '%M-%d-%y')"),
                         
                          rs.getString("tblcustomer.fld_fname")+" "
                                    + ""+rs.getString("tblcustomer.fld_mname") +" "+
                                    rs.getString("tblcustomer.fld_lname"),
                           rs.getString("tblcustomer.fld_zone")+ " "+
                            rs.getString("tblcustomer.fld_st") +" "+
                          
                            rs.getString("tblcustomer.fld_city")+ " "+
                            rs.getString("tblcustomer.fld_province"),
                            rs.getString("tblcustomer.fld_customer_code")
                            
                            
                            
                          
                    
                    });
                                  }
                tblinvoiceno.setModel(dtm);
                hidecolumn();
                rs.close();
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
              
                
                
            
            
            
            
            
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblinvoiceno = new javax.swing.JTable(){public boolean isCellEditable(int rowIndex, int colIndex){return false;}};
        btnopensupcan = new javax.swing.JButton();
        btnselectinvoice = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtinvoicedate = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        txtinvoiceno = new javax.swing.JTextField();
        btnselectcustomer = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btncreate = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        txtcustomercode = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtcustomerdetails = new javax.swing.JTextArea();
        rbtgov = new javax.swing.JRadioButton();
        rbtprivate = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Select Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblinvoiceno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblinvoiceno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblinvoiceno.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblinvoiceno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblinvoicenoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblinvoicenoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblinvoiceno);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 390));

        btnopensupcan.setText("Cancel");
        btnopensupcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopensupcanActionPerformed(evt);
            }
        });
        jPanel1.add(btnopensupcan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 90, 40));

        btnselectinvoice.setText("Select");
        btnselectinvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselectinvoiceActionPerformed(evt);
            }
        });
        jPanel1.add(btnselectinvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 100, 40));

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 130, -1));

        jLabel2.setText("Search");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 510, 540));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Add Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Customer Code");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, -1));

        txtinvoicedate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("M-dd-yyyy"))));
        txtinvoicedate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtinvoicedateFocusLost(evt);
            }
        });
        txtinvoicedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinvoicedateActionPerformed(evt);
            }
        });
        jPanel2.add(txtinvoicedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 170, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Customer Details");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 89, -1));

        txtinvoiceno.setEditable(false);
        txtinvoiceno.setFocusable(false);
        txtinvoiceno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinvoicenoActionPerformed(evt);
            }
        });
        txtinvoiceno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtinvoicenoKeyPressed(evt);
            }
        });
        jPanel2.add(txtinvoiceno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 170, -1));

        btnselectcustomer.setText("...");
        btnselectcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselectcustomerActionPerformed(evt);
            }
        });
        jPanel2.add(btnselectcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 30, -1));

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel2.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 191, 40));

        btncreate.setText("Create");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        jPanel2.add(btncreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 190, 40));

        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel2.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 191, 40));

        txtcustomercode.setEditable(false);
        txtcustomercode.setFocusable(false);
        txtcustomercode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcustomercodeFocusLost(evt);
            }
        });
        txtcustomercode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcustomercodeKeyPressed(evt);
            }
        });
        jPanel2.add(txtcustomercode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 170, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Invoice No");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Invoice Date");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtcustomerdetails.setEditable(false);
        txtcustomerdetails.setColumns(20);
        txtcustomerdetails.setLineWrap(true);
        txtcustomerdetails.setRows(5);
        txtcustomerdetails.setFocusable(false);
        jScrollPane2.setViewportView(txtcustomerdetails);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 80));

        rbtgov.setText("Government");
        rbtgov.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtgovItemStateChanged(evt);
            }
        });
        jPanel2.add(rbtgov, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        rbtprivate.setSelected(true);
        rbtprivate.setText("Private");
        rbtprivate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtprivateItemStateChanged(evt);
            }
        });
        rbtprivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtprivateActionPerformed(evt);
            }
        });
        jPanel2.add(rbtprivate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 370, 540));

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Trajan Pro", 1, 36)); // NOI18N
        jLabel12.setText("Select/Create Invoice");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbluser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbluser.setText("Welcome");
        jPanel4.add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        lbldate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbldate.setText("Welcome");
        jPanel4.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Welcome");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        lbltime.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbltime.setText("Welcome");
        jPanel4.add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 990, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtinvoicedateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtinvoicedateFocusLost

     
    }//GEN-LAST:event_txtinvoicedateFocusLost

    private void txtinvoicedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinvoicedateActionPerformed

    }//GEN-LAST:event_txtinvoicedateActionPerformed

    private void txtinvoicenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinvoicenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinvoicenoActionPerformed

    private void txtinvoicenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinvoicenoKeyPressed
      
    }//GEN-LAST:event_txtinvoicenoKeyPressed
frmCustomerDetails select  = new frmCustomerDetails();
    private void btnselectcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselectcustomerActionPerformed
            
            select.setVisible(true);
//       frmSelectCustomer select= new frmSelectCustomer();
//       select.setVisible(true);
    }//GEN-LAST:event_btnselectcustomerActionPerformed

    private void txtcustomercodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcustomercodeFocusLost

        
    }//GEN-LAST:event_txtcustomercodeFocusLost
 ActionListener dateTime =new  ActionListener() {
            
          
      @Override
      public void actionPerformed(ActionEvent e) {
          SimpleDateFormat df=new SimpleDateFormat("M-dd-yyyy");
          SimpleDateFormat df2 = new SimpleDateFormat("EEEE");
          SimpleDateFormat df3 = new SimpleDateFormat("hh:mm:ss a");
           Date now= new Date();
          String strdate= df.format(new Date());
          String strday= df2.format(now);
          
          String strtime= df3.format(now);
          
          lbltime.setText(strtime);
           lbldate.setText(strdate+", "+strday);//To change body of generated methods, choose Tools | Templates.
      }
  };
    private void txtcustomercodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcustomercodeKeyPressed
        

    }//GEN-LAST:event_txtcustomercodeKeyPressed

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed

        sqlcode="select * from tblinvoiceno where fld_invoice_no='"+ txtinvoiceno.getText().trim() +"'";
        String[] textboxes={txtcustomercode.getText().trim(),
                            txtcustomerdetails.getText().trim(),
                            txtinvoicedate.getText().trim()
                            
                            
        };
        if (BotiqueSystem.isTextEmpty(textboxes)) {
            JOptionPane.showMessageDialog(null, "Empty input not allowed!");
        }
        
        else if(BotiqueSystem.isduplicate(sqlcode, conn)){
                    JOptionPane.showMessageDialog(null, "Duplicate entry for Invoice no "+ txtinvoiceno.getText());
                    txtinvoiceno.requestFocus();
            
            
        
        }
        else{
            sqlcode="insert into tblinvoiceno set fld_invoice_no='"+ txtinvoiceno.getText() +"', "
                    + "fld_invoice_date=str_to_date('"+ txtinvoicedate.getText() +"', '%m-%d-%Y'), "
                    + "fld_invoice_type='"+ BotiqueSystem.invoicetype +"', "
                    + "fld_customer_code='"+ txtcustomercode.getText() +"'";
            //JOptionPane.showMessageDialog(null, sqlcode);

            if (BotiqueSystem.addupdatedel(sqlcode, conn)) {
                JOptionPane.showMessageDialog(null, "Added!");
                if (rbtprivate.isSelected()) {
                      takenum();
                }
              
                txtinvoiceno.setText(BotiqueSystem.nextInvoiceNo());
                 
                 btncancelActionPerformed(evt);
                 
               
            }
        }
 
        
       
        
    }//GEN-LAST:event_btncreateActionPerformed
    public void takenum(){
        sqlcode="insert into tblautoinvoiceno set fld_taken=1";
        BotiqueSystem.addupdatedel(sqlcode, conn);
    }
    
    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
       
        
        sqlcode="select * from tblinvoice where fld_invoice_no='"+ refid +"'";
        try {
            rs=BotiqueSystem.selectquery(sqlcode, conn);
             if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "This invoice can no longer be edited!");
                }
             else{
                          if (tblinvoiceno.getSelectedRowCount()>0) {
                        if (btnedit.getText().equals("Edit")) {
                        btnedit.setText("Update");
                        btncreate.setEnabled(false);
                        rbtgov.setEnabled(false);
                        rbtprivate.setEnabled(false);
                        txtinvoiceno.setEditable(false);




                            txtinvoiceno.setText(tblinvoiceno.getValueAt(tblinvoiceno.getSelectedRow(), 0).toString());
                            txtinvoicedate.setText(tblinvoiceno.getValueAt(tblinvoiceno.getSelectedRow(), 1).toString());
                            txtcustomercode.setText(tblinvoiceno.getValueAt(tblinvoiceno.getSelectedRow(), 4).toString());
                            txtcustomerdetails.setText(tblinvoiceno.getValueAt(tblinvoiceno.getSelectedRow(), 3).toString());



                    }
                    else{
                        sqlcode="update tblinvoiceno set fld_invoice_no='"+ txtinvoiceno.getText() +"', "
                            + "fld_invoice_date=str_to_date('"+ txtinvoicedate.getText() +"', '%m-%d-%Y'), "
                            + "fld_customer_code='"+ txtcustomercode.getText() +"' where fld_invoice_no='"+ refid +"'";
                        if (BotiqueSystem.addupdatedel(sqlcode, conn)) {
                            JOptionPane.showMessageDialog(null, "Updated");
                             btncancelActionPerformed(evt);

                        }
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "No item selected!");
                }
                 
             }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
       
        
        
           
    }//GEN-LAST:event_btneditActionPerformed

    private void tblinvoicenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblinvoicenoMouseClicked
        if (evt.getClickCount()==2) {
            btnselectinvoiceActionPerformed(null);
        }
        evt.getClickCount();
    }//GEN-LAST:event_tblinvoicenoMouseClicked

    private void btnselectinvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselectinvoiceActionPerformed
        if (tblinvoiceno.getSelectedRowCount()>0) {
            frmStockOut.txtinvoiceno.setText(tblinvoiceno.getValueAt(tblinvoiceno.getSelectedRow(), 0).toString());

            //frmStockOut.
            this.dispose();
            frmStockOut.txtinvoiceno.requestFocus();
        }
        else{
            JOptionPane.showMessageDialog(null, "No Selection");
        }
    }//GEN-LAST:event_btnselectinvoiceActionPerformed

    private void btnopensupcanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopensupcanActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnopensupcanActionPerformed
 public void hidecolumn() {
       
        TableColumn col = tblinvoiceno.getColumnModel().getColumn(0);
         col = tblinvoiceno.getColumnModel().getColumn(2);
        col.setPreferredWidth(150);
        col.setMaxWidth(150);
        col.setMinWidth(150);
        
       
       col = tblinvoiceno.getColumnModel().getColumn(3);
        col.setPreferredWidth(200);
        col.setMaxWidth(200);
        col.setMinWidth(200);
        col = tblinvoiceno.getColumnModel().getColumn(4);
        col.setPreferredWidth(100);
        col.setMaxWidth(100);
        col.setMinWidth(100);
}
    
    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased

        if (txtsearch.getText().equals("")) {
            loadinvoice();
        }
        else{
             DefaultTableModel dtm = new DefaultTableModel(){
                public boolean isCellEditable(int rowIndex, int colIndex){
                    return false;
                }
            };
          
            dtm.addColumn("Invoice no");
            dtm.addColumn("Invoice Date");
            dtm.addColumn("Name");
            
           
            
              dtm.addColumn("Address");
               dtm.addColumn("Customer Code");
                
                
                
                sqlcode="select "
                       
                        + " tblinvoiceno.fld_invoice_no,"
                        + " date_format(tblinvoiceno.fld_invoice_date, '%m-%d-%Y'),"
                        + " tblcustomer.fld_customer_code, "
                        + "tblcustomer.fld_fname, "
                        + "tblcustomer.fld_mname,"
                        + " tblcustomer.fld_lname, "
                        + "tblcustomer.fld_zone, "
                        + "tblcustomer.fld_st, "
                        + "tblcustomer.fld_city, "
                        + "tblcustomer.fld_province "
                        + "from tblinvoiceno inner join"
                        + " tblcustomer on tblinvoiceno.fld_customer_code=tblcustomer.fld_customer_code "
                        + "where fld_mname like '%"+ txtsearch.getText().trim() +"%' or "
                        + "fld_fname like '%"+ txtsearch.getText().trim() +"%' or "
                        + "fld_lname like '%"+ txtsearch.getText().trim() +"%' "
                        + "  order by tblinvoiceno.fld_invoice_no desc";
            try {
                  rs=BotiqueSystem.selectquery(sqlcode, conn);
                  
                while (rs.next()) {
                    dtm.addRow(new Object[]{
                       
                        rs.getString("tblinvoiceno.fld_invoice_no"),
                        rs.getString("date_format(tblinvoiceno.fld_invoice_date, '%M-%d-%y')"),
                         
                          rs.getString("tblcustomer.fld_fname")+" "
                                    + ""+rs.getString("tblcustomer.fld_mname") +" "+
                                    rs.getString("tblcustomer.fld_lname"),
                          rs.getString("tblcustomer.fld_zone")+ " "+
                            rs.getString("tblcustomer.fld_st") +" "+
                          
                            rs.getString("tblcustomer.fld_city")+ " "+
                            rs.getString("tblcustomer.fld_province"),
                            rs.getString("tblcustomer.fld_customer_code")
                             
                            
                            
                          
                    
                    });
                                  }
                tblinvoiceno.setModel(dtm);
                hidecolumn();
                rs.close();
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
              
        }
    }//GEN-LAST:event_txtsearchKeyReleased

    private void tblinvoicenoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblinvoicenoMousePressed
        if (btnedit.getText().equals("Update")) {
            JOptionPane.showMessageDialog(null, "Finish/Cancel update first!");
        }
        else{
            if (tblinvoiceno.getSelectedRowCount()>0) {
            refid=tblinvoiceno.getValueAt(tblinvoiceno.getSelectedRow(), 0).toString();
            //JOptionPane.showMessageDialog(null, refid);
            
            btnedit.setEnabled(true);
        }
        else{
            refid="0";
        }
        }
    }//GEN-LAST:event_tblinvoicenoMousePressed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        btnedit.setText("Edit");
       txtinvoiceno.setText("INV"+BotiqueSystem.nextInvoiceNo());
        btnedit.setEnabled(false);
        btncreate.setEnabled(true);
        rbtprivate.setSelected(true);
         rbtgov.setEnabled(true);
         rbtprivate.setEnabled(true);
        loadinvoice();
        cleartxt();
    }//GEN-LAST:event_btncancelActionPerformed
String invoicetype="Private";
   
    
    private void rbtgovItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtgovItemStateChanged
        if (rbtgov.isSelected()) {
            BotiqueSystem. invoicetype="Gov";
            txtinvoiceno.setText("");
            txtinvoiceno.setEditable(true);
            txtinvoiceno.setFocusable(true);

        }
    }//GEN-LAST:event_rbtgovItemStateChanged

    private void rbtprivateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtprivateItemStateChanged
        if (rbtprivate.isSelected()) {
            BotiqueSystem. invoicetype="Private";
            
            txtinvoiceno.setText("INV"+BotiqueSystem.nextInvoiceNo());
              txtinvoiceno.setEditable(false);
               txtinvoiceno.setFocusable(false);

        }
    }//GEN-LAST:event_rbtprivateItemStateChanged

    private void rbtprivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtprivateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtprivateActionPerformed

    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCreateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCreateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCreateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCreateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCreateInvoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg1;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btncreate;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnopensupcan;
    private javax.swing.JButton btnselectcustomer;
    public static javax.swing.JButton btnselectinvoice;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbltime;
    private javax.swing.JLabel lbluser;
    private javax.swing.JRadioButton rbtgov;
    private javax.swing.JRadioButton rbtprivate;
    private javax.swing.JTable tblinvoiceno;
    public static javax.swing.JTextField txtcustomercode;
    public static javax.swing.JTextArea txtcustomerdetails;
    private javax.swing.JFormattedTextField txtinvoicedate;
    private javax.swing.JTextField txtinvoiceno;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
